camera_name: "gemini336"
depth_registration: true
serial_number: ""
usb_port: ""
device_num: "1"
enable_point_cloud: true
enable_colored_point_cloud: true
point_cloud_qos: "SENSOR_DATA"
connection_delay: "100"
color_width: "1920"
color_height: "1080"
color_fps: "30"
color_format: "MJPG"
enable_color: true
color_qos: "BEST_EFFORT" #"SENSOR_DATA"
color_camera_info_qos: "default"
enable_color_auto_exposure: true
depth_width: "1280"
depth_height: "800"
depth_fps: "15"
depth_format: "Y16"
enable_depth: true
depth_qos: "BEST_EFFORT" #"SENSOR_DATA"
depth_camera_info_qos: "default"
left_ir_width: "1280"
left_ir_height: "800"
left_ir_fps: "15"
left_ir_format: "Y8"
enable_left_ir: false
left_ir_qos: "SENSOR_DATA"
left_ir_camera_info_qos: "default"
right_ir_width: "1280"
right_ir_height: "800"
right_ir_fps: "15"
right_ir_format: "Y8"
enable_right_ir: false
right_ir_qos: "SENSOR_DATA"
right_ir_camera_info_qos: "default"
enable_ir_auto_exposure: true
enable_sync_output_accel_gyro: true
enable_accel: false
accel_rate: "200hz"
accel_range: "4g"
enable_gyro: false
gyro_rate: "200hz"
gyro_range: "1000dps"
liner_accel_cov: "0.01"
angular_vel_cov: "0.01"
publish_tf: false
tf_publish_rate: "10.0"
ir_info_url: ""
color_info_url: ""
log_level: "none"
enable_publish_extrinsic: false
enable_d2c_viewer: false
enable_ldp: true
sync_mode: "free_run"
depth_delay_us: "0"
color_delay_us: "0"
trigger2image_delay_us: "0"
trigger_out_delay_us: "0"
trigger_out_enabled: false
enable_frame_sync: true
ordered_pc: false
use_hardware_time: false
enable_depth_scale: true
retry_on_usb3_detection_failure: true
